<a href="https://colab.research.google.com/github/Raju-mia-RK/DeepLearning/blob/main/introduction_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
print("Hello")

Hello


In [42]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [43]:
import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [44]:
print(torch.__version__)

2.11.0+cpu


In [45]:
scaler=torch.tensor(7)
scaler

tensor(7)

In [46]:
scaler.ndim

0

In [47]:
scaler.shape

torch.Size([])

In [48]:
vector=torch.tensor([3,5])
vector

tensor([3, 5])

In [49]:
vector.ndim

1

In [50]:
vector.shape

torch.Size([2])

In [51]:
tensor=torch.tensor([[[[3,3,4],
                       [5,6,7],[12,23,45]]]])
tensor

tensor([[[[ 3,  3,  4],
          [ 5,  6,  7],
          [12, 23, 45]]]])

In [52]:
tensor.ndim

4

In [53]:
tensor.shape

torch.Size([1, 1, 3, 3])

Random Tensor

In [54]:
random_tensor=torch.rand([3,4])
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [55]:
random_tensor.ndim,random_tensor.shape

(2, torch.Size([3, 4]))

In [56]:
random_image_tensor=torch.rand([224,224,3])
random_image_tensor.ndim,random_image_tensor.shape

(3, torch.Size([224, 224, 3]))

In [57]:
int_torch=torch.tensor([3.,5,6],dtype=None,device=None,requires_grad=False)
int_torch.dtype

torch.float32

In [58]:
array=np.arange(1.0,8)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [59]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
tensor([[0.1336, 0.9666, 0.9754, 0.8474],
        [0.8988, 0.1105, 0.4563, 0.9719],
        [0.3968, 0.1496, 0.4743, 0.9973]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


set random seed

In [60]:
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
torch_random_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
torch_random_D=torch.rand(3,4)
print(torch_random_C)
print(torch_random_D)
print(torch_random_C==torch_random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [61]:
if torch.cuda.is_available():
  print('GPU is available')
  print(f"Using GPU {torch.cudu.get_device_name(0)}")
else:
  print("GPU is not available using CPU")

GPU is not available using CPU


In [63]:
x=torch.tensor(3.0,requires_grad=True)

In [64]:
y=x**2

In [65]:
x

tensor(3., requires_grad=True)

In [66]:
y

tensor(9., grad_fn=<PowBackward0>)

In [67]:
y.backward()

In [68]:
y


tensor(9., grad_fn=<PowBackward0>)

In [70]:
x.grad

tensor(6.)